version: '2.4'

networks:
  fabric:
    name: ac_fabric
    driver: bridge

volumes:
  orderer1:
  orderer2:
  orderer3:
  peer0:
  peer1:
  peer2:
  peer3:
  peer4:
  peer5:
  peer6:
  peer7:
  peer8:

services:
  ####################
  # ORDERERS
  ####################
  orderer1.example.com: &orderer
    container_name: orderer1.example.com
    image: hyperledger/fabric-orderer:2.5
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    volumes:
      - ./crypto-config/ordererOrganizations/example.com/orderers/orderer1.example.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/example.com/orderers/orderer1.example.com/tls:/var/hyperledger/orderer/tls
      - ./channel-artifacts/genesis.block:/etc/hyperledger/fabric/genesisblock
      - orderer1:/var/hyperledger/production
    ports:
      - "7050:7050"
    networks:
      - fabric

  orderer2.example.com:
    <<: *orderer
    container_name: orderer2.example.com
    volumes:
      - ./crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/tls:/var/hyperledger/orderer/tls
      - ./channel-artifacts/genesis.block:/etc/hyperledger/fabric/genesisblock
      - orderer2:/var/hyperledger/production
    ports:
      - "8050:7050"
    networks:
      - fabric

  orderer3.example.com:
    <<: *orderer
    container_name: orderer3.example.com
    volumes:
      - ./crypto-config/ordererOrganizations/example.com/orderers/orderer3.example.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/example.com/orderers/orderer3.example.com/tls:/var/hyperledger/orderer/tls
      - ./channel-artifacts/genesis.block:/etc/hyperledger/fabric/genesisblock
      - orderer3:/var/hyperledger/production
    ports:
      - "9050:7050"
    networks:
      - fabric

  ####################
  # PEERS
  ####################
 
  peer0.orgmain.example.com: &peer
    container_name: peer0.orgmain.example.com
    image: hyperledger/fabric-peer:2.5
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=ac_fabric
      - CORE_PEER_ID=peer0.orgmain.example.com
      - CORE_PEER_ADDRESS=peer0.orgmain.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.orgmain.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.orgmain.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.orgmain.example.com:7051
      - CORE_PEER_LOCALMSPID=OrgMainMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/peer/tls/ca.crt
    volumes:
      - ./chaincode:/chaincode
      - ./crypto-config/peerOrganizations/orgmain.example.com/users/Admin@orgmain.example.com/msp:/etc/hyperledger/crypto-config/peerOrganizations/orgmain.example.com/users/Admin@orgmain.example.com/msp
      - /var/run:/host/var/run
      - ./crypto-config/peerOrganizations/orgmain.example.com/peers/peer0.orgmain.example.com/msp:/etc/hyperledger/peer/msp
      - ./crypto-config/peerOrganizations/orgmain.example.com/peers/peer0.orgmain.example.com/tls:/etc/hyperledger/peer/tls
      - peer0:/var/hyperledger/production
    ports:
      - "7051:7051"
    networks:
      - fabric

  peer1.orgmain.example.com:
    <<: *peer
    container_name: peer1.orgmain.example.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=ac_fabric
      - CORE_PEER_ID=peer1.orgmain.example.com
      - CORE_PEER_ADDRESS=peer1.orgmain.example.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.orgmain.example.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.orgmain.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.orgmain.example.com:8051
      - CORE_PEER_LOCALMSPID=OrgMainMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/peer/tls/ca.crt
    volumes:
      - ./chaincode:/chaincode
      - ./crypto-config/peerOrganizations/orgmain.example.com/users/Admin@orgmain.example.com/msp:/etc/hyperledger/crypto-config/peerOrganizations/orgmain.example.com/users/Admin@orgmain.example.com/msp
      - /var/run:/host/var/run
      - ./crypto-config/peerOrganizations/orgmain.example.com/peers/peer1.orgmain.example.com/msp:/etc/hyperledger/peer/msp
      - ./crypto-config/peerOrganizations/orgmain.example.com/peers/peer1.orgmain.example.com/tls:/etc/hyperledger/peer/tls
      - peer1:/var/hyperledger/production
    ports:
      - "8051:8051"
    networks:
      - fabric
      
  peer2.orgmain.example.com:
    <<: *peer
    container_name: peer2.orgmain.example.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=ac_fabric
      - CORE_PEER_ID=peer2.orgmain.example.com
      - CORE_PEER_ADDRESS=peer2.orgmain.example.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer2.orgmain.example.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.orgmain.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.orgmain.example.com:9051
      - CORE_PEER_LOCALMSPID=OrgMainMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/peer/tls/ca.crt
    volumes:
      - ./chaincode:/chaincode
      - ./crypto-config/peerOrganizations/orgmain.example.com/users/Admin@orgmain.example.com/msp:/etc/hyperledger/crypto-config/peerOrganizations/orgmain.example.com/users/Admin@orgmain.example.com/msp
      - /var/run:/host/var/run
      - ./crypto-config/peerOrganizations/orgmain.example.com/peers/peer2.orgmain.example.com/msp:/etc/hyperledger/peer/msp
      - ./crypto-config/peerOrganizations/orgmain.example.com/peers/peer2.orgmain.example.com/tls:/etc/hyperledger/peer/tls
      - peer2:/var/hyperledger/production
    ports:
      - "9051:9051"
    networks:
      - fabric
      
  peer3.orgmain.example.com:
    <<: *peer
    container_name: peer3.orgmain.example.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=ac_fabric
      - CORE_PEER_ID=peer3.orgmain.example.com
      - CORE_PEER_ADDRESS=peer3.orgmain.example.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer3.orgmain.example.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.orgmain.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer3.orgmain.example.com:10051
      - CORE_PEER_LOCALMSPID=OrgMainMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/peer/tls/ca.crt
    volumes:
      - ./chaincode:/chaincode
      - ./crypto-config/peerOrganizations/orgmain.example.com/users/Admin@orgmain.example.com/msp:/etc/hyperledger/crypto-config/peerOrganizations/orgmain.example.com/users/Admin@orgmain.example.com/msp
      - /var/run:/host/var/run
      - ./crypto-config/peerOrganizations/orgmain.example.com/peers/peer3.orgmain.example.com/msp:/etc/hyperledger/peer/msp
      - ./crypto-config/peerOrganizations/orgmain.example.com/peers/peer3.orgmain.example.com/tls:/etc/hyperledger/peer/tls
      - peer3:/var/hyperledger/production
    ports:
      - "10051:10051"
    networks:
      - fabric
      
  peer4.orgmain.example.com:
    <<: *peer
    container_name: peer4.orgmain.example.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=ac_fabric
      - CORE_PEER_ID=peer4.orgmain.example.com
      - CORE_PEER_ADDRESS=peer4.orgmain.example.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer4.orgmain.example.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.orgmain.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer4.orgmain.example.com:11051
      - CORE_PEER_LOCALMSPID=OrgMainMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/peer/tls/ca.crt
    volumes:
      - ./chaincode:/chaincode
      - ./crypto-config/peerOrganizations/orgmain.example.com/users/Admin@orgmain.example.com/msp:/etc/hyperledger/crypto-config/peerOrganizations/orgmain.example.com/users/Admin@orgmain.example.com/msp
      - /var/run:/host/var/run
      - ./crypto-config/peerOrganizations/orgmain.example.com/peers/peer4.orgmain.example.com/msp:/etc/hyperledger/peer/msp
      - ./crypto-config/peerOrganizations/orgmain.example.com/peers/peer4.orgmain.example.com/tls:/etc/hyperledger/peer/tls
      - peer4:/var/hyperledger/production
    ports:
      - "11051:11051"
    networks:
      - fabric

  peer5.orgmain.example.com:
    <<: *peer
    container_name: peer5.orgmain.example.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=ac_fabric
      - CORE_PEER_ID=peer5.orgmain.example.com
      - CORE_PEER_ADDRESS=peer5.orgmain.example.com:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=peer5.orgmain.example.com:12052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.orgmain.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer5.orgmain.example.com:12051
      - CORE_PEER_LOCALMSPID=OrgMainMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/peer/tls/ca.crt
    volumes:
      - ./chaincode:/chaincode
      - ./crypto-config/peerOrganizations/orgmain.example.com/users/Admin@orgmain.example.com/msp:/etc/hyperledger/crypto-config/peerOrganizations/orgmain.example.com/users/Admin@orgmain.example.com/msp
      - /var/run:/host/var/run
      - ./crypto-config/peerOrganizations/orgmain.example.com/peers/peer5.orgmain.example.com/msp:/etc/hyperledger/peer/msp
      - ./crypto-config/peerOrganizations/orgmain.example.com/peers/peer5.orgmain.example.com/tls:/etc/hyperledger/peer/tls
      - peer5:/var/hyperledger/production
    ports:
      - "12051:12051"
    networks:
      - fabric
       
  peer6.orgmain.example.com:
    <<: *peer
    container_name: peer6.orgmain.example.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=ac_fabric
      - CORE_PEER_ID=peer6.orgmain.example.com
      - CORE_PEER_ADDRESS=peer6.orgmain.example.com:13051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:13051
      - CORE_PEER_CHAINCODEADDRESS=peer6.orgmain.example.com:13052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:13052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.orgmain.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer6.orgmain.example.com:13051
      - CORE_PEER_LOCALMSPID=OrgMainMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/peer/tls/ca.crt
    volumes:
      - ./chaincode:/chaincode
      - ./crypto-config/peerOrganizations/orgmain.example.com/users/Admin@orgmain.example.com/msp:/etc/hyperledger/crypto-config/peerOrganizations/orgmain.example.com/users/Admin@orgmain.example.com/msp
      - /var/run:/host/var/run
      - ./crypto-config/peerOrganizations/orgmain.example.com/peers/peer6.orgmain.example.com/msp:/etc/hyperledger/peer/msp
      - ./crypto-config/peerOrganizations/orgmain.example.com/peers/peer6.orgmain.example.com/tls:/etc/hyperledger/peer/tls
      - peer6:/var/hyperledger/production
    ports:
      - "13051:13051"
    networks:
      - fabric

  peer7.orgmain.example.com:
    <<: *peer
    container_name: peer7.orgmain.example.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=ac_fabric
      - CORE_PEER_ID=peer7.orgmain.example.com
      - CORE_PEER_ADDRESS=peer7.orgmain.example.com:14051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:14051
      - CORE_PEER_CHAINCODEADDRESS=peer7.orgmain.example.com:14052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:14052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.orgmain.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer7.orgmain.example.com:14051
      - CORE_PEER_LOCALMSPID=OrgMainMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/peer/tls/ca.crt
    volumes:
      - ./chaincode:/chaincode
      - ./crypto-config/peerOrganizations/orgmain.example.com/users/Admin@orgmain.example.com/msp:/etc/hyperledger/crypto-config/peerOrganizations/orgmain.example.com/users/Admin@orgmain.example.com/msp
      - /var/run:/host/var/run
      - ./crypto-config/peerOrganizations/orgmain.example.com/peers/peer7.orgmain.example.com/msp:/etc/hyperledger/peer/msp
      - ./crypto-config/peerOrganizations/orgmain.example.com/peers/peer7.orgmain.example.com/tls:/etc/hyperledger/peer/tls
      - peer7:/var/hyperledger/production
    ports:
      - "14051:14051"
    networks:
      - fabric
      
  peer8.orgmain.example.com:
    <<: *peer
    container_name: peer8.orgmain.example.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=ac_fabric
      - CORE_PEER_ID=peer8.orgmain.example.com
      - CORE_PEER_ADDRESS=peer8.orgmain.example.com:15051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:15051
      - CORE_PEER_CHAINCODEADDRESS=peer8.orgmain.example.com:15052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:15052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.orgmain.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer8.orgmain.example.com:15051
      - CORE_PEER_LOCALMSPID=OrgMainMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/peer/tls/ca.crt
    volumes:
      - ./chaincode:/chaincode
      - ./crypto-config/peerOrganizations/orgmain.example.com/users/Admin@orgmain.example.com/msp:/etc/hyperledger/crypto-config/peerOrganizations/orgmain.example.com/users/Admin@orgmain.example.com/msp
      - /var/run:/host/var/run
      - ./crypto-config/peerOrganizations/orgmain.example.com/peers/peer8.orgmain.example.com/msp:/etc/hyperledger/peer/msp
      - ./crypto-config/peerOrganizations/orgmain.example.com/peers/peer8.orgmain.example.com/tls:/etc/hyperledger/peer/tls
      - peer8:/var/hyperledger/production
    ports:
      - "15051:15051"
    networks:
      - fabric

    ####################
  # CLI CONTAINER
  ####################
  cli:
    build:
      context: .
      dockerfile: Dockerfile.cli
    container_name: cli
    image: hyperledger/fabric-tools:2.5
    tty: true
    stdin_open: true
    privileged: true
    user: root
    environment:
      - DOCKER_BUILDKIT=0  
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=ac_fabric
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DOCKER_TLS_VERIFY=
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.orgmain.example.com:7051
      - CORE_PEER_LOCALMSPID=OrgMainMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peerOrganizations/orgmain.example.com/peers/peer0.orgmain.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peerOrganizations/orgmain.example.com/peers/peer0.orgmain.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peerOrganizations/orgmain.example.com/peers/peer0.orgmain.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peerOrganizations/orgmain.example.com/users/Admin@orgmain.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - ./crypto-config:/etc/hyperledger/crypto
      - ./channel-artifacts:/etc/hyperledger/channel-artifacts
      - ./chaincode:/chaincode
      - /var/run/:/host/var/run/
    networks:
      - fabric
    depends_on:
      - orderer1.example.com
      - orderer2.example.com
      - orderer3.example.com
      - peer0.orgmain.example.com
      - peer1.orgmain.example.com
      - peer2.orgmain.example.com
      - peer3.orgmain.example.com
      - peer4.orgmain.example.com
      - peer5.orgmain.example.com
      - peer6.orgmain.example.com
      - peer7.orgmain.example.com
      - peer8.orgmain.example.com



